name = "peptitrack"
compatibility_date = "2025-12-31"

# Cloudflare Pages needs this to treat wrangler.toml as Pages config
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "peptitrack-db"
database_id = "40f7fae4-c21d-46c1-bbc8-90ece3666713"
